"""empty message

Revision ID: 1abdbc0b2eca
Revises: 
Create Date: 2018-04-14 15:59:08.107323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abdbc0b2eca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=5), nullable=False),
    sa.Column('complement', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('postal_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_name', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=14), nullable=False),
    sa.Column('cnae', sa.String(length=10), nullable=False),
    sa.Column('ie', sa.String(length=10), nullable=False),
    sa.Column('im', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('employee_name', sa.String(length=30), nullable=False),
    sa.Column('employee_department', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=30), nullable=False),
    sa.Column('serial_number', sa.String(length=15), nullable=False),
    sa.Column('branch', sa.String(length=15), nullable=False),
    sa.Column('model', sa.String(length=15), nullable=False),
    sa.Column('quantity', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('coast', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('contact')
    op.drop_table('provider')
    op.drop_table('address')
    # ### end Alembic commands ###
